services:
  - type: web
    name: yesaya-ministry-api
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yesaya-ministry-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yesaya-ministry-api.onrender.com,*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: PYTHON_VERSION
        value: "3.12.0"

 databases:
  - name: yesaya-ministry-db
    plan: free
    databaseName: yesaya_ministry
    user: yesaya_ministry
